AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Slack App

Parameters:
  SlackClientId:
    Type: String
    Default: ""
  SlackClientSecret:
    Type: String
    Default: ""
  SlackSigningSecret:
    Type: String
    Default: ""

Globals:
  Function:
    Timeout: 480
    MemorySize: 1024
    Environment:
      Variables:
        SLACK_CLIENT_ID: !Ref SlackClientId
        SLACK_CLIENT_SECRET: !Ref SlackClientSecret
        SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
        OAUTH_STATE_S3_BUCKET_NAME: !Ref OauthStateS3Bucket
        INSTALLATION_S3_BUCKET_NAME: !Ref InstallationS3Bucket

Resources:
  OauthStateS3Bucket:
    Type: 'AWS::S3::Bucket' 

  InstallationS3Bucket:
    Type: 'AWS::S3::Bucket'

  CloudFormationSlackAppFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CloudFormationSlackAppFunctionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SlackAppFunctionPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: "*"
                  Resource: "*"
                  
  CloudFormationSlackAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.12
      CodeUri: ./src
      Description: Slack App Function
      Role: !GetAtt CloudFormationSlackAppFunctionRole.Arn
      Events:
        SlackEvents:
          Type: Api
          Properties:
            Path: /slack/events
            Method: POST
        SlackOauthRedirect:
          Type: Api
          Properties:
            Path: /slack/oauth_redirect
            Method: GET
        SlackInstall:
          Type: Api
          Properties:
            Path: /slack/install
            Method: GET

Outputs:
  OauthStateS3Bucket:
    Description: "Oauth State S3 Bucket"
    Value: !GetAtt OauthStateS3Bucket.Arn  
  InstallationS3Bucket:
    Description: "Installation S3 Bucket"
    Value: !GetAtt InstallationS3Bucket.Arn  
  SlackAppFunction:
    Description: "Slack App Function ARN"
    Value: !GetAtt CloudFormationSlackAppFunction.Arn
  SlackAppFunctionRole:
    Description: "IAM Role for Slack App Function"
    Value: !GetAtt CloudFormationSlackAppFunctionRole.Arn